/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/skillfarm/api/menu/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Skillfarm navigation menu */
        get: operations["skillfarm_api_general_get_menu"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/user/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user data and permissions */
        get: operations["skillfarm_api_general_get_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/settings/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current user's Skillfarm settings */
        get: operations["skillfarm_api_general_get_user_settings"];
        /** Update current user's Skillfarm settings */
        put: operations["skillfarm_api_general_update_user_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/characters/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List skillfarm characters with filterable metrics */
        get: operations["skillfarm_api_characters_list_characters"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/characters/{character_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get character details including skillqueue and farm setup */
        get: operations["skillfarm_api_characters_get_character_detail"];
        put?: never;
        post?: never;
        /** Remove character from skillfarm */
        delete: operations["skillfarm_api_characters_delete_character"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/characters/{character_id}/acknowledge-extractions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge ready skill extractions for a character */
        post: operations["skillfarm_api_characters_acknowledge_extractions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/characters/{character_id}/acknowledge-paused/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acknowledge paused or empty queue for a character */
        post: operations["skillfarm_api_characters_acknowledge_paused"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/characters/{character_id}/toggle-notification/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle notifications for a character */
        post: operations["skillfarm_api_characters_toggle_notification"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/characters/{character_id}/setup/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get configured skillset for character */
        get: operations["skillfarm_api_characters_get_skillsetup"];
        put?: never;
        /** Update configured skillset for character */
        post: operations["skillfarm_api_characters_update_skillsetup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/acknowledge-all-extractions/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk acknowledge all pending ready extractions */
        post: operations["skillfarm_api_characters_acknowledge_all_extractions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/calculator/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get skillfarm market prices and profit margins */
        get: operations["skillfarm_api_calculator_get_calculator_data"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/overview/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users with visible skillfarm characters */
        get: operations["skillfarm_api_overview_get_overview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/overview/{user_id}/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the skillfarm characters of a single user */
        get: operations["skillfarm_api_overview_get_overview_user"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/admin/stats/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get administrative statistics for all Skillfarm characters */
        get: operations["skillfarm_api_admin_get_admin_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/admin/update-all/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue full update task for all Skillfarm characters */
        post: operations["skillfarm_api_admin_trigger_update_all"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/skillfarm/api/admin/update-prices/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Queue market prices update task */
        post: operations["skillfarm_api_admin_trigger_update_prices"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * MenuLink
         * @description A single link item in the menu bar.
         */
        MenuLink: {
            /** Name */
            name: string;
            /** Link */
            link?: string | null;
            /**
             * Is External
             * @default false
             */
            is_external: boolean;
        };
        /**
         * MenuSchema
         * @description Top navigation menu structure.
         */
        MenuSchema: {
            /**
             * Left Links
             * @default []
             */
            left_links: components["schemas"]["MenuLink"][];
            /**
             * Right Links
             * @default []
             */
            right_links: components["schemas"]["MenuLink"][];
        };
        /**
         * UserData
         * @description User profile data including character identity and admin state.
         */
        UserData: {
            /** User Id */
            user_id: number;
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Corporation Id */
            corporation_id: number;
            /** Corporation Name */
            corporation_name: string;
            /** Alliance Id */
            alliance_id?: number | null;
            /** Alliance Name */
            alliance_name?: string | null;
            /** Portrait */
            portrait?: string | null;
            /**
             * Is Admin
             * @default false
             */
            is_admin: boolean;
            /**
             * Has Corp Access
             * @default false
             */
            has_corp_access: boolean;
        };
        /**
         * UserSettingsSchema
         * @description Notification settings of the current user.
         */
        UserSettingsSchema: {
            /** Disable Notifications */
            disable_notifications: boolean;
        };
        /**
         * UserSettingsUpdateRequest
         * @description User-editable notification preferences.
         */
        UserSettingsUpdateRequest: {
            /** Disable Notifications */
            disable_notifications: boolean;
        };
        /**
         * CharacterFilter
         * @description Filter schema for skillfarm characters.
         */
        CharacterFilter: {
            /**
             * Search
             * @description Filter by character name, corporation name, or ticker
             */
            search?: string | null;
            /**
             * Training Status
             * @description Filter by active training status
             * @default all
             * @enum {string}
             */
            training_status: "all" | "training" | "paused";
            /**
             * Extraction Status
             * @description Filter by extraction readiness and acknowledgment review state
             * @default all
             * @enum {string}
             */
            extraction_status: "all" | "pending" | "acknowledged" | "none";
            /**
             * Notification Status
             * @description Filter by notification enabled/disabled
             * @default all
             * @enum {string}
             */
            notification_status: "all" | "enabled" | "disabled";
            /**
             * Corporation Id
             * @description Filter by corporation ID
             */
            corporation_id?: number | null;
        };
        /**
         * CharacterListResponse
         * @description Response payload for character dashboard.
         */
        CharacterListResponse: {
            /** Characters */
            characters: components["schemas"]["CharacterSummarySchema"][];
            /** Total Count */
            total_count: number;
            /**
             * Active Training Count
             * @default 0
             */
            active_training_count: number;
            /** Paused Training Count */
            paused_training_count: number;
            /**
             * Unacknowledged Paused Count
             * @default 0
             */
            unacknowledged_paused_count: number;
            /** Pending Extractions Count */
            pending_extractions_count: number;
            /** Acknowledged Extractions Count */
            acknowledged_extractions_count: number;
        };
        /**
         * CharacterSummarySchema
         * @description Summary of a skillfarm character for table and card views.
         */
        CharacterSummarySchema: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /** Corporation Id */
            corporation_id: number;
            /** Corporation Name */
            corporation_name: string;
            /** Corporation Ticker */
            corporation_ticker: string;
            /** Portrait Url */
            portrait_url: string;
            /** Total Sp */
            total_sp: number;
            /** Is Training */
            is_training: boolean;
            /** Training Start Date */
            training_start_date?: string | null;
            /** Training Finish Date */
            training_finish_date?: string | null;
            /** Queue Finish Date */
            queue_finish_date?: string | null;
            /** Current Training Skill */
            current_training_skill?: string | null;
            /**
             * Progress Percent
             * @default 0
             */
            progress_percent: number;
            /**
             * Extractions Ready Count
             * @default 0
             */
            extractions_ready_count: number;
            /**
             * Extraction Acknowledged
             * @default false
             */
            extraction_acknowledged: boolean;
            /** Extraction Acknowledged At */
            extraction_acknowledged_at?: string | null;
            /**
             * Queue Paused Acknowledged
             * @default false
             */
            queue_paused_acknowledged: boolean;
            /**
             * Notification Enabled
             * @default false
             */
            notification_enabled: boolean;
            /**
             * Update Status
             * @default ok
             */
            update_status: string;
            /** Last Update */
            last_update?: string | null;
        };
        /**
         * CharacterDetailResponse
         * @description Full detail response for a single character.
         */
        CharacterDetailResponse: {
            character: components["schemas"]["CharacterSummarySchema"];
            /**
             * Skillqueue
             * @default []
             */
            skillqueue: components["schemas"]["SkillQueueEntrySchema"][];
            /**
             * Farmed Skills
             * @default []
             */
            farmed_skills: components["schemas"]["FarmedSkillSchema"][];
            /**
             * Configured Skillset
             * @default []
             */
            configured_skillset: string[];
        };
        /**
         * FarmedSkillSchema
         * @description Schema for trained skill in character skillset.
         */
        FarmedSkillSchema: {
            /** Skill Id */
            skill_id: number;
            /** Skill Name */
            skill_name: string;
            /** Active Level */
            active_level: number;
            /** Trained Level */
            trained_level: number;
            /** Skillpoints */
            skillpoints: number;
            /**
             * Is Extractable
             * @default false
             */
            is_extractable: boolean;
        };
        /**
         * SkillQueueEntrySchema
         * @description Schema for individual skillqueue entries.
         */
        SkillQueueEntrySchema: {
            /** Skill Id */
            skill_id: number;
            /** Skill Name */
            skill_name: string;
            /** Finished Level */
            finished_level: number;
            /** Finished Level Roman */
            finished_level_roman: string;
            /** Queue Position */
            queue_position: number;
            /** Start Date */
            start_date?: string | null;
            /** Finish Date */
            finish_date?: string | null;
            /**
             * Start Sp
             * @default 0
             */
            start_sp: number;
            /**
             * End Sp
             * @default 0
             */
            end_sp: number;
            /**
             * Training Start Sp
             * @default 0
             */
            training_start_sp: number;
            /**
             * Progress Percent
             * @default 0
             */
            progress_percent: number;
            /**
             * Is Active
             * @default false
             */
            is_active: boolean;
            /**
             * Is Extractable
             * @default false
             */
            is_extractable: boolean;
        };
        /**
         * ActionResponse
         * @description Generic action response schema.
         */
        ActionResponse: {
            /** Success */
            success: boolean;
            /** Message */
            message: string;
        };
        /**
         * SkillSetupSchema
         * @description Configured farm skillset for a character.
         */
        SkillSetupSchema: {
            /** Character Id */
            character_id: number;
            /** Character Name */
            character_name: string;
            /**
             * Skillset
             * @default []
             */
            skillset: string[];
            /**
             * Available Skills
             * @default []
             */
            available_skills: string[];
        };
        /**
         * SkillSetupUpdateRequest
         * @description Request payload to update configured skillset.
         */
        SkillSetupUpdateRequest: {
            /** Selected Skills */
            selected_skills: string[];
        };
        /**
         * CalculatorItemSchema
         * @description Market price information for a trade item.
         */
        CalculatorItemSchema: {
            /** Type Id */
            type_id: number;
            /** Name */
            name: string;
            /** Buy */
            buy: number;
            /** Sell */
            sell: number;
            /** Updated At */
            updated_at?: string | null;
        };
        /**
         * CalculatorResponse
         * @description Skillfarm calculation and ROI summary.
         */
        CalculatorResponse: {
            /**
             * Error
             * @default false
             */
            error: boolean;
            /** Error Message */
            error_message?: string | null;
            plex?: components["schemas"]["CalculatorItemSchema"] | null;
            injector?: components["schemas"]["CalculatorItemSchema"] | null;
            extractor?: components["schemas"]["CalculatorItemSchema"] | null;
            /**
             * Month Calc
             * @default 0
             */
            month_calc: number;
            /**
             * Month12 Calc
             * @default 0
             */
            month12_calc: number;
            /**
             * Month24 Calc
             * @default 0
             */
            month24_calc: number;
        };
        /**
         * OverviewResponse
         * @description Response payload for the overview of all visible users.
         */
        OverviewResponse: {
            /** Users */
            users: components["schemas"]["OverviewUserSchema"][];
        };
        /**
         * OverviewUserSchema
         * @description Aggregated skillfarm state of a single user (grouped by main character).
         */
        OverviewUserSchema: {
            /** User Id */
            user_id: number;
            /** Username */
            username: string;
            /** Main Character Id */
            main_character_id?: number | null;
            /** Main Character Name */
            main_character_name: string;
            /**
             * Corporation Name
             * @default
             */
            corporation_name: string;
            /**
             * Corporation Ticker
             * @default
             */
            corporation_ticker: string;
            /** Portrait Url */
            portrait_url?: string | null;
            /**
             * Character Count
             * @default 0
             */
            character_count: number;
            /**
             * Training Count
             * @default 0
             */
            training_count: number;
            /**
             * Paused Count
             * @default 0
             */
            paused_count: number;
            /**
             * Pending Extractions Count
             * @default 0
             */
            pending_extractions_count: number;
        };
        /**
         * OverviewUserCharactersResponse
         * @description Characters of a single user for the overview detail page.
         */
        OverviewUserCharactersResponse: {
            /** Characters */
            characters: components["schemas"]["CharacterSummarySchema"][];
            /** Total Count */
            total_count: number;
            /**
             * Active Training Count
             * @default 0
             */
            active_training_count: number;
            /** Paused Training Count */
            paused_training_count: number;
            /**
             * Unacknowledged Paused Count
             * @default 0
             */
            unacknowledged_paused_count: number;
            /** Pending Extractions Count */
            pending_extractions_count: number;
            /** Acknowledged Extractions Count */
            acknowledged_extractions_count: number;
            user: components["schemas"]["OverviewUserSchema"];
        };
        /** AdminStatsResponse */
        AdminStatsResponse: {
            /** Total Characters */
            total_characters: number;
            /** Active Characters */
            active_characters: number;
            /** In Training Count */
            in_training_count: number;
            /** Paused Training Count */
            paused_training_count: number;
            /** Total Sp */
            total_sp: number;
            /** Total Pending Extractions */
            total_pending_extractions: number;
        };
        /** AdminUpdateRequest */
        AdminUpdateRequest: {
            /**
             * Force Refresh
             * @default false
             */
            force_refresh: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    skillfarm_api_general_get_menu: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MenuSchema"];
                };
            };
        };
    };
    skillfarm_api_general_get_user: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserData"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_general_get_user_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_general_update_user_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserSettingsUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSettingsSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_characters_list_characters: {
        parameters: {
            query?: {
                /** @description Filter by character name, corporation name, or ticker */
                search?: string | null;
                /** @description Filter by active training status */
                training_status?: "all" | "training" | "paused";
                /** @description Filter by extraction readiness and acknowledgment review state */
                extraction_status?: "all" | "pending" | "acknowledged" | "none";
                /** @description Filter by notification enabled/disabled */
                notification_status?: "all" | "enabled" | "disabled";
                /** @description Filter by corporation ID */
                corporation_id?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterListResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_characters_get_character_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CharacterDetailResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_characters_delete_character: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_characters_acknowledge_extractions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_characters_acknowledge_paused: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_characters_toggle_notification: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_characters_get_skillsetup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SkillSetupSchema"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_characters_update_skillsetup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                character_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SkillSetupUpdateRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_characters_acknowledge_all_extractions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_calculator_get_calculator_data: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalculatorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_overview_get_overview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_overview_get_overview_user: {
        parameters: {
            query?: {
                /** @description Filter by character name, corporation name, or ticker */
                search?: string | null;
                /** @description Filter by active training status */
                training_status?: "all" | "training" | "paused";
                /** @description Filter by extraction readiness and acknowledgment review state */
                extraction_status?: "all" | "pending" | "acknowledged" | "none";
                /** @description Filter by notification enabled/disabled */
                notification_status?: "all" | "enabled" | "disabled";
                /** @description Filter by corporation ID */
                corporation_id?: number | null;
            };
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OverviewUserCharactersResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_admin_get_admin_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminStatsResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_admin_trigger_update_all: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AdminUpdateRequest"] | null;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    skillfarm_api_admin_trigger_update_prices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
