# Generated by Django 4.2.28 on 2026-02-25 09:17

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skillfarm", "0001_init_v2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="evetypeprice",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
