# Generated by Django 5.2.13 on 2026-09-20 14:04

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skillfarm", "0002_alter_evetypeprice_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="general",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("basic_access", "Can access this app, Skillfarm."),
                    ("corp_access", "Has access to all characters in the corporation."),
                    ("admin_access", "Has access to all characters."),
                ),
                "verbose_name": "AA-Skillfarm",
                "verbose_name_plural": "AA-Skillfarm",
            },
        ),
    ]
