# Generated by Django 5.1.7 on 2025-03-18 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eveuniverse", "0010_alter_eveindustryactivityduration_eve_type_and_more"),
        ("skillfarm", "0003_characterskill_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EveTypePrice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("buy", models.DecimalField(decimal_places=2, max_digits=20)),
                ("sell", models.DecimalField(decimal_places=2, max_digits=20)),
                ("updated_at", models.DateTimeField()),
                (
                    "eve_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eveuniverse.evetype",
                    ),
                ),
            ],
        ),
    ]
