# Generated by Django 5.2.13 on 2026-10-03 16:19

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_alter_characterownership_user_and_more"),
        ("skillfarm", "0003_alter_general_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillfarmaudit",
            name="current_training_skill",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="Name and level of current skill in training.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="skillfarmaudit",
            name="extraction_acknowledged",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether ready extractions have been acknowledged by the user.",
            ),
        ),
        migrations.AddField(
            model_name="skillfarmaudit",
            name="extraction_acknowledged_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Timestamp when extractions were acknowledged.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="skillfarmaudit",
            name="extraction_acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="User who acknowledged the ready extractions.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="authentication.user",
            ),
        ),
        migrations.AddField(
            model_name="skillfarmaudit",
            name="extractions_ready_count",
            field=models.PositiveIntegerField(
                db_index=True,
                default=0,
                help_text="Number of farm skills ready for extraction.",
            ),
        ),
        migrations.AddField(
            model_name="skillfarmaudit",
            name="is_training",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether the character currently has an active training queue.",
            ),
        ),
        migrations.AddField(
            model_name="skillfarmaudit",
            name="queue_finish_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Finish date of the entire skill queue.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="skillfarmaudit",
            name="queue_paused_acknowledged",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Whether paused training has been acknowledged by the user.",
            ),
        ),
        migrations.AddField(
            model_name="skillfarmaudit",
            name="total_sp",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Total accumulated skill points."
            ),
        ),
        migrations.AddField(
            model_name="skillfarmaudit",
            name="training_finish_date",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                help_text="Finish date of the currently training skill.",
                null=True,
            ),
        ),
    ]
