# Generated by Django 5.2.13 on 2026-10-03 19:38

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0026_alter_characterownership_user_and_more"),
        (
            "skillfarm",
            "0004_remove_characterskillqueueentry_has_no_skillqueue_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSettings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("disable_notifications", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skillfarm_settings",
                        to="authentication.user",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
    ]
