# Generated by Django 4.2.20 on 2025-05-04 21:51

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skillfarm", "0005_alter_characterskill_character_and_more"),
    ]

    operations = []
