# Generated by Django 5.2.13 on 2026-10-10 20:25

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skillfarm", "0005_usersettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="characterupdatestatus",
            name="character",
            field=models.ForeignKey(
                db_column="character_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="skillfarm_update_status",
                to="skillfarm.skillfarmaudit",
            ),
        ),
        migrations.RenameField(
            model_name="characterupdatestatus",
            old_name="character",
            new_name="owner",
        ),
    ]
