# Generated by Django 4.2.27 on 2026-01-30 06:29

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skillfarm", "0008_alter_characterupdatestatus_section"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillfarmaudit",
            name="is_read",
            field=models.BooleanField(
                default=False, help_text="Mark Character as read"
            ),
        ),
    ]
