# Generated by Django 4.2.28 on 2026-02-25 08:39

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0012_alter_constellation_region"),
        ("skillfarm", "0009_skillfarmaudit_is_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evetypeprice",
            options={"default_permissions": ()},
        ),
        migrations.AlterField(
            model_name="characterskill",
            name="eve_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="characterskillqueueentry",
            name="eve_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="eve_sde.itemtype",
            ),
        ),
        migrations.AlterField(
            model_name="evetypeprice",
            name="eve_type",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="eve_sde.itemtype",
            ),
        ),
    ]
